CREATE PROC FI_SP_ConsBeneficiario
	@ID BIGINT
AS
BEGIN
    IF(ISNULL(@ID,0) = 0)
        SELECT ID, CPF, NOME, IDCLIENTE FROM BENEFICIARIOS WITH(NOLOCK) ORDER BY NOME
    ELSE
        SELECT  ID, CPF, NOME, IDCLIENTE FROM BENEFICIARIOS WITH(NOLOCK) WHERE ID = @ID ORDER BY NOME
END